# Generated by Django 3.0.1 on 2020-01-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('enrollmentnumber', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=13)),
                ('status', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('dt', models.CharField(max_length=100)),
            ],
        ),
    ]
