# Generated by Django 3.0.1 on 2020-02-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('enrollmentnumber', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=10000)),
                ('status', models.IntegerField()),
                ('dt', models.CharField(max_length=100)),
            ],
        ),
    ]
